server:
  port: 8081

logging:
  level:
    org:
      springframework:
        data:
          neo4j: DEBUG
      neo4j:
        ogm:
          drivers:
            bolt:
              request:
                BoltRequest: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

spring:
  data:
    neo4j:
      repositories:
        type: reactive
org:
  neo4j:
    driver:
      uri: neo4j://localhost:7687
      authentication:
        username: neo4j
        password: test